version: '2'
services:
  mongo:
    image: mongo:2.2.7
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo:/data/db
    restart: always
  elasticsearch:
    image: elasticsearch:1.4
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: always
  chesshub:
    build: ./chesshub
    ports:
      - 80:3000
    links:
      - elasticsearch:elasticsearch
      - mongo:mongo
    restart: always
volumes:
  elasticsearch:
  mongo:
  data:
